services:
  api:
    build:
      context: .
      target: api
    restart: always
    ports:
      - "3008:3008"
    env_file:
      - .env
    environment:
      - PORT=3008
      - NODE_ENV=production

  workers:
    build:
      context: .
      target: workers
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
