/**
 * Voice Routes
 *
 * Voice training examples and settings
 */

import express, { Response, Router } from 'express';
import { createClient } from '@supabase/supabase-js';
import { z } from 'zod';
import { Queue } from 'bullmq';
import IORedis from 'ioredis';
import { AuthenticatedRequest } from '../middleware/auth.js';

const router: Router = express.Router();

const SUPABASE_URL = process.env.SUPABASE_URL || '';
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_KEY || '';
const REDIS_URL = process.env.UPSTASH_REDIS_URL || '';

// BullMQ queue for voice document processing - lazy init
let _redisConnection: IORedis | null = null;
let _voiceProcessorQueue: Queue | null = null;

function getVoiceQueue(): Queue | null {
  if (!REDIS_URL) {
    console.warn('[Voice] UPSTASH_REDIS_URL not configured, queue disabled');
    return null;
  }
  if (!_voiceProcessorQueue) {
    _redisConnection = new IORedis(REDIS_URL, { maxRetriesPerRequest: null });
    _voiceProcessorQueue = new Queue('voice-processor', { connection: _redisConnection });
  }
  return _voiceProcessorQueue;
}

// Constants
const MAX_FILE_SIZE = 10 * 1024 * 1024; // 10MB
const MAX_DOCUMENTS_PER_USER = 20;

function getSupabase() {
  return createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);
}

const exampleSchema = z.object({
  text: z.string().min(10).max(1000),
  tone: z.enum(['friendly', 'neutral', 'hostile']),
});

const settingsSchema = z.object({
  formality: z.number().min(0).max(1).optional(),
  brevity: z.number().min(0).max(1).optional(),
  emoji_usage: z.number().min(0).max(1).optional(),
  aggression: z.number().min(0).max(1).optional(),
  never_say: z.array(z.string()).optional(),
  always_use: z.array(z.string()).optional(),
  signature_phrases: z.array(z.string()).optional(),
  response_lengths: z
    .object({
      friendly: z.object({ min: z.number(), max: z.number() }),
      neutral: z.object({ min: z.number(), max: z.number() }),
      hostile: z.object({ min: z.number(), max: z.number() }),
    })
    .optional(),
});

/**
 * GET /api/voice/examples
 * List voice examples
 */
router.get('/examples', async (req, res: Response) => {
  try {
    const { accountId } = (req as unknown as AuthenticatedRequest).auth;
    const tone = req.query.tone as string | undefined;

    let query = getSupabase()
      .from('voice_examples')
      .select('id, text, tone, source, is_active, created_at')
      .eq('account_id', accountId)
      .order('created_at', { ascending: false });

    if (tone) {
      query = query.eq('tone', tone);
    }

    const { data, error } = await query;

    if (error) throw error;

    res.json({ examples: data || [] });
  } catch (error) {
    console.error('[Voice] Failed to list examples:', error);
    res.status(500).json({ error: 'Failed to list examples' });
  }
});

/**
 * POST /api/voice/examples
 * Add a voice example
 */
router.post('/examples', async (req, res: Response) => {
  try {
    const { accountId } = (req as unknown as AuthenticatedRequest).auth;
    const parsed = exampleSchema.safeParse(req.body);

    if (!parsed.success) {
      return res.status(400).json({ error: 'Invalid request body' });
    }

    const { text, tone } = parsed.data;

    // Insert example (embedding will be generated by background job)
    const { data, error } = await getSupabase()
      .from('voice_examples')
      .insert({
        account_id: accountId,
        text,
        tone,
        source: 'manual',
        is_active: true,
      })
      .select('id, text, tone, source, is_active, created_at')
      .single();

    if (error) throw error;

    // TODO: Queue embedding generation job

    res.json({ success: true, example: data });
  } catch (error) {
    console.error('[Voice] Failed to add example:', error);
    res.status(500).json({ error: 'Failed to add example' });
  }
});

/**
 * DELETE /api/voice/examples/:id
 * Delete a voice example
 */
router.delete('/examples/:id', async (req, res: Response) => {
  try {
    const { accountId } = (req as unknown as AuthenticatedRequest).auth;
    const { id } = req.params;

    const { error } = await getSupabase()
      .from('voice_examples')
      .delete()
      .eq('id', id)
      .eq('account_id', accountId);

    if (error) throw error;

    res.json({ success: true });
  } catch (error) {
    console.error('[Voice] Failed to delete example:', error);
    res.status(500).json({ error: 'Failed to delete example' });
  }
});

/**
 * GET /api/voice/settings
 * Get voice settings
 */
router.get('/settings', async (req, res: Response) => {
  try {
    const { accountId } = (req as unknown as AuthenticatedRequest).auth;

    const { data, error } = await getSupabase()
      .from('voice_settings')
      .select('*')
      .eq('account_id', accountId)
      .single();

    if (error && error.code !== 'PGRST116') throw error;

    // Return defaults if no settings exist
    const settings = data || {
      formality: 0.3,
      brevity: 0.2,
      emoji_usage: 0.4,
      aggression: 0.5,
      never_say: [],
      always_use: [],
      signature_phrases: [],
      response_lengths: {
        friendly: { min: 3, max: 15 },
        neutral: { min: 5, max: 25 },
        hostile: { min: 2, max: 10 },
      },
    };

    res.json({ settings });
  } catch (error) {
    console.error('[Voice] Failed to get settings:', error);
    res.status(500).json({ error: 'Failed to get settings' });
  }
});

/**
 * PUT /api/voice/settings
 * Update voice settings
 */
router.put('/settings', async (req, res: Response) => {
  try {
    const { accountId } = (req as unknown as AuthenticatedRequest).auth;
    const parsed = settingsSchema.safeParse(req.body);

    if (!parsed.success) {
      return res.status(400).json({ error: 'Invalid request body' });
    }

    const { data, error } = await getSupabase()
      .from('voice_settings')
      .upsert(
        {
          account_id: accountId,
          ...parsed.data,
          updated_at: new Date().toISOString(),
        },
        { onConflict: 'account_id' }
      )
      .select('*')
      .single();

    if (error) throw error;

    res.json({ success: true, settings: data });
  } catch (error) {
    console.error('[Voice] Failed to update settings:', error);
    res.status(500).json({ error: 'Failed to update settings' });
  }
});

/**
 * GET /api/voice/documents
 * List uploaded documents
 */
router.get('/documents', async (req, res: Response) => {
  try {
    const { accountId } = (req as unknown as AuthenticatedRequest).auth;

    const { data, error } = await getSupabase()
      .from('voice_documents')
      .select('*')
      .eq('account_id', accountId)
      .order('created_at', { ascending: false });

    if (error) throw error;

    res.json({ documents: data || [] });
  } catch (error) {
    console.error('[Voice] Failed to list documents:', error);
    res.status(500).json({ error: 'Failed to list documents' });
  }
});

/**
 * POST /api/voice/documents/upload
 * Upload a file for voice training (with base64 file data)
 */
router.post('/documents/upload', async (req, res: Response) => {
  try {
    const { accountId } = (req as unknown as AuthenticatedRequest).auth;
    const { filename, fileSize, fileData } = req.body;

    if (!filename || !fileData) {
      return res.status(400).json({ error: 'filename and fileData required' });
    }

    // Check file size limit (10MB)
    if (fileSize && fileSize > MAX_FILE_SIZE) {
      return res.status(400).json({
        error: `File too large. Maximum size is ${MAX_FILE_SIZE / 1024 / 1024}MB`
      });
    }

    // Check supported file types
    const ext = filename.split('.').pop()?.toLowerCase();
    const supportedTypes = ['txt', 'md', 'pdf', 'docx'];
    if (!ext || !supportedTypes.includes(ext)) {
      return res.status(400).json({
        error: `Unsupported file type. Supported: ${supportedTypes.join(', ')}`
      });
    }

    // Check document count limit
    const { count, error: countError } = await getSupabase()
      .from('voice_documents')
      .select('*', { count: 'exact', head: true })
      .eq('account_id', accountId);

    if (countError) throw countError;

    if ((count || 0) >= MAX_DOCUMENTS_PER_USER) {
      return res.status(400).json({
        error: `Maximum ${MAX_DOCUMENTS_PER_USER} documents allowed. Delete some to upload more.`
      });
    }

    // Decode base64 and upload to Supabase Storage
    const buffer = Buffer.from(fileData, 'base64');
    const storagePath = `accounts/${accountId}/documents/${Date.now()}-${filename}`;

    const { error: uploadError } = await getSupabase()
      .storage
      .from('voice-documents')
      .upload(storagePath, buffer, {
        contentType: ext === 'pdf' ? 'application/pdf' :
                     ext === 'docx' ? 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' :
                     'text/plain',
      });

    if (uploadError) {
      console.error('[Voice] Storage upload failed:', uploadError);
      throw new Error(`Failed to upload file: ${uploadError.message}`);
    }

    // Create document record
    const { data, error } = await getSupabase()
      .from('voice_documents')
      .insert({
        account_id: accountId,
        filename,
        storage_path: storagePath,
        status: 'pending',
      })
      .select('*')
      .single();

    if (error) throw error;

    // Queue voice processor job (if queue available)
    const queue = getVoiceQueue();
    let jobId = null;
    if (queue) {
      const job = await queue.add('process', {
        accountId,
        documentId: data.id,
        storagePath,
      });
      jobId = job.id;
      console.log(`[Voice] Uploaded ${filename} and queued for processing (job: ${job.id})`);
    } else {
      console.log(`[Voice] Uploaded ${filename} (queue not available)`);
    }

    res.json({
      success: true,
      document: data,
      jobId
    });
  } catch (error) {
    console.error('[Voice] Failed to upload document:', error);
    res.status(500).json({ error: 'Failed to upload document' });
  }
});

/**
 * DELETE /api/voice/documents/:id
 * Delete a voice document
 */
router.delete('/documents/:id', async (req, res: Response) => {
  try {
    const { accountId } = (req as unknown as AuthenticatedRequest).auth;
    const { id } = req.params;

    // Get document to find storage path
    const { data: doc, error: findError } = await getSupabase()
      .from('voice_documents')
      .select('storage_path')
      .eq('id', id)
      .eq('account_id', accountId)
      .single();

    if (findError || !doc) {
      return res.status(404).json({ error: 'Document not found' });
    }

    // Delete from storage
    if (doc.storage_path) {
      await getSupabase()
        .storage
        .from('voice-documents')
        .remove([doc.storage_path]);
    }

    // Delete related voice examples
    await getSupabase()
      .from('voice_examples')
      .delete()
      .eq('account_id', accountId)
      .eq('source', 'document');

    // Delete document record
    const { error } = await getSupabase()
      .from('voice_documents')
      .delete()
      .eq('id', id)
      .eq('account_id', accountId);

    if (error) throw error;

    res.json({ success: true });
  } catch (error) {
    console.error('[Voice] Failed to delete document:', error);
    res.status(500).json({ error: 'Failed to delete document' });
  }
});

/**
 * POST /api/voice/documents
 * Upload a document for voice training (legacy: expects storagePath)
 * (Creates record and queues processing)
 */
router.post('/documents', async (req, res: Response) => {
  try {
    const { accountId } = (req as unknown as AuthenticatedRequest).auth;
    const { filename, storagePath, fileSize } = req.body;

    if (!filename || !storagePath) {
      return res.status(400).json({ error: 'filename and storagePath required' });
    }

    // Check file size limit (10MB)
    if (fileSize && fileSize > MAX_FILE_SIZE) {
      return res.status(400).json({
        error: `File too large. Maximum size is ${MAX_FILE_SIZE / 1024 / 1024}MB`
      });
    }

    // Check supported file types
    const ext = filename.split('.').pop()?.toLowerCase();
    const supportedTypes = ['txt', 'md', 'pdf', 'docx'];
    if (!ext || !supportedTypes.includes(ext)) {
      return res.status(400).json({
        error: `Unsupported file type. Supported: ${supportedTypes.join(', ')}`
      });
    }

    // Check document count limit
    const { count, error: countError } = await getSupabase()
      .from('voice_documents')
      .select('*', { count: 'exact', head: true })
      .eq('account_id', accountId);

    if (countError) throw countError;

    if ((count || 0) >= MAX_DOCUMENTS_PER_USER) {
      return res.status(400).json({
        error: `Maximum ${MAX_DOCUMENTS_PER_USER} documents allowed. Delete some to upload more.`
      });
    }

    // Create document record
    const { data, error } = await getSupabase()
      .from('voice_documents')
      .insert({
        account_id: accountId,
        filename,
        storage_path: storagePath,
        status: 'pending',
      })
      .select('*')
      .single();

    if (error) throw error;

    // Queue voice processor job (if queue available)
    const queue = getVoiceQueue();
    let jobId = null;
    if (queue) {
      const job = await queue.add('process', {
        accountId,
        documentId: data.id,
        storagePath,
      });
      jobId = job.id;
      console.log(`[Voice] Queued document ${data.id} for processing (job: ${job.id})`);
    } else {
      console.log(`[Voice] Document ${data.id} saved (queue not available)`);
    }

    res.json({
      success: true,
      document: data,
      jobId
    });
  } catch (error) {
    console.error('[Voice] Failed to upload document:', error);
    res.status(500).json({ error: 'Failed to upload document' });
  }
});

/**
 * POST /api/voice/test
 * Test drive a response with current voice settings
 */
router.post('/test', async (req, res: Response) => {
  try {
    const { accountId } = (req as unknown as AuthenticatedRequest).auth;
    const { originalPost, replyText, classification } = req.body;

    if (!originalPost || !replyText) {
      return res.status(400).json({
        error: 'originalPost and replyText required',
      });
    }

    // For now, return a placeholder - in production this would
    // call the responder with the user's voice settings
    res.json({
      success: true,
      response: `[Test mode] Would generate ${classification || 'neutral'} response to: "${replyText.substring(0, 50)}..."`,
      note: 'Connect voice processor worker for live responses',
    });
  } catch (error) {
    console.error('[Voice] Failed to test response:', error);
    res.status(500).json({ error: 'Failed to test response' });
  }
});

export default router;
